-- Create the users table with all required fields
CREATE TABLE IF NOT EXISTS public.users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  
  -- Common fields
  full_name text NOT NULL,
  email text NOT NULL UNIQUE,
  password text NOT NULL,
  wallet_address text,
  user_type text NOT NULL CHECK (user_type IN ('doctor', 'patient')),

  -- Doctor-specific (optional for patients)
  medical_license_url text,
  hospital_affiliation_url text,
  govt_id_url text,
  is_verified boolean NOT NULL DEFAULT false,
  specialization text,
  reg_id text,

  -- Patient-specific (optional for doctors)
  age integer,
  phone_number text,
  gender text,
  device_id text
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_users_email ON public.users(email);
CREATE INDEX IF NOT EXISTS idx_users_user_type ON public.users(user_type);
CREATE INDEX IF NOT EXISTS idx_users_is_verified ON public.users(is_verified);
